[project]
name = "textual-forms"
version = "0.1.0"
description = "Forms handling for textual"
authors = [
    {name = "Steve Holden",email = "steve@holdenweb.com"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12,<4.0.0"
dependencies = [
    "textual (>=2.1.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.dev.dependencies]
textual-dev = "^1.7.0"

